# Generated by Django 6.0.3 on 2026-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Es: 'Prossime Scadenze', 'Documenti in Attesa'",
                        max_length=100,
                        verbose_name="Titolo Widget",
                    ),
                ),
                (
                    "widget_key",
                    models.SlugField(
                        help_text="Identificativo univoco usato nel template HTML (es. 'upcoming_events')",
                        max_length=100,
                        unique=True,
                        verbose_name="Chiave Widget",
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        default=list,
                        help_text="Lista di ruoli (base, senza _a/_b) che possono vedere questo widget.",
                        verbose_name="Ruoli Target",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordine di visualizzazione nella griglia (0 = primo in alto/a sinistra)",
                        verbose_name="Posizione",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se disattivato, il widget non verrà renderizzato",
                        verbose_name="Attivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Widget Dashboard",
                "verbose_name_plural": "Widget Dashboard",
                "ordering": ["position", "title"],
            },
        ),
    ]
