# Generated by Django 6.0.3 on 2026-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dashboardwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="min_plan_level",
            field=models.PositiveIntegerField(
                choices=[(1, "Starter"), (2, "Pro"), (3, "Enterprise")],
                default=1,
                help_text="Livello minimo del piano abbonamento per visualizzare questo widget (1=Starter, 2=Pro, 3=Enterprise)",
                verbose_name="Piano Minimo",
            ),
        ),
    ]
