# Generated by Django 6.0.3 on 2026-06-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dashboardwidget_min_plan_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboardwidget",
            name="min_plan_level",
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="allowed_plan_levels",
            field=models.JSONField(
                default=list,
                help_text="Lista dei piani che possono vedere il widget",
                verbose_name="Piani Abilitati",
            ),
        ),
    ]
