# Generated by Django 6.0.3 on 2026-05-14 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0002_initial"),
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6f42c1", max_length=7)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("ordinarie", "Ordinarie"),
                            ("straordinarie", "Straordinarie"),
                            ("straordinarie_concordare", "Straordinarie da concordare"),
                        ],
                        default="ordinarie",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria Spesa",
                "verbose_name_plural": "Categorie Spese",
                "ordering": ["group", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "split_percentage_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% caricata sul Genitore A per questa spesa (se nulla, usa quella del figlio)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("expense_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In Sospeso"),
                            ("accepted", "Accettata"),
                            ("rejected", "Rifiutata"),
                            ("paid", "Pagata"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archiviata il"
                    ),
                ),
                (
                    "effective_split_pct_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentuale effettiva applicata a questa versione",
                        max_digits=5,
                        null=True,
                        verbose_name="Quota Genitore A (snapshot)",
                    ),
                ),
                (
                    "approved_by_parent_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by_parent_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="children.childprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="families.family",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ultima modifica da",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_versions",
                        to="expenses.expense",
                    ),
                ),
                (
                    "expense_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"],
                        name="expenses_ex_status_f414e0_idx",
                    )
                ],
            },
        ),
    ]
