# Generated by Django 6.0.3 on 2026-05-16 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={"ordering": ["group__label", "display_name"]},
        ),
        migrations.RemoveField(
            model_name="expensecategory",
            name="name",
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category_color_snapshot",
            field=models.CharField(
                blank=True,
                default="#6f42c1",
                max_length=7,
                verbose_name="Colore categoria",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category_name_snapshot",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nome categoria"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="group_snapshot",
            field=models.CharField(
                blank=True,
                default="ordinarie",
                max_length=100,
                verbose_name="Gruppo categoria",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_versions",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="color",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="display_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="expenses.expensecategorygroup",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseCategoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Creata"),
                            ("updated", "Modificata"),
                            ("deleted", "Disattivata"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_name", models.CharField(blank=True, max_length=255)),
                ("new_name", models.CharField(blank=True, max_length=255)),
                ("old_color", models.CharField(blank=True, max_length=20)),
                ("new_color", models.CharField(blank=True, max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
