# Generated by Django 6.0.3 on 2026-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expenses",
            "0002_expensecategorygroup_alter_expensecategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
