# Generated by Django 6.0.3 on 2026-05-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expensecategory_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
    ]
