# Generated by Django 6.0.3 on 2026-05-31 06:02

import core.fields
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymessage",
            name="content",
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(
                storage=core.storage.EncryptedFileSystemStorage(
                    location="media/encrypted_chat"
                ),
                upload_to="message_attachments/",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="content",
            field=core.fields.EncryptedTextField(),
        ),
    ]
