# Generated by Django 6.0.3 on 2026-05-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_familymessage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
