# Generated by Django 6.0.3 on 2026-05-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_privatemessage_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrivateMessage",
        ),
    ]
