# Generated by Django 6.0.3 on 2026-06-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_delete_privatemessage"),
        ("expenses", "0004_remove_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymessage",
            name="linked_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_messages",
                to="expenses.expense",
            ),
        ),
        migrations.AddField(
            model_name="familymessage",
            name="thread_type",
            field=models.CharField(
                choices=[
                    ("family", "👨\u200d👩\u200d👧\u200d👦 Gruppo Famiglia (Tutti)"),
                    ("legal_a", "⚖️ Legale A (Avv.A + Gen.A)"),
                    ("legal_b", "⚖️ Legale B (Avv.B + Gen.B)"),
                    ("mediation", "🤝 Mediazione (Mediatore + Gen.A + Gen.B)"),
                    ("consulting", "💼 Consulenza (Consulente + Gen.A + Gen.B)"),
                ],
                db_index=True,
                default="family",
                max_length=20,
            ),
        ),
    ]
