# Generated by Django 6.0.3 on 2026-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_familymessage_linked_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymessage",
            name="thread_type",
            field=models.CharField(
                choices=[
                    ("family", "👨\u200d👩\u200d👧\u200d👦 Gruppo Famiglia (Tutti)"),
                    ("legal_a", "⚖️ Legale A (Avv.A + Gen.A)"),
                    ("legal_b", "⚖️ Legale B (Avv.B + Gen.B)"),
                    ("mediation", "🤝 Mediazione (Mediatore + Gen.A + Gen.B)"),
                    ("consulting", "💼 Consulenza (Consulente + Gen.A + Gen.B)"),
                    (
                        "mediation_private",
                        "🔒 Mediazione Privata (Mediatore + Genitore)",
                    ),
                    (
                        "consultant_private",
                        "🔒 Consulenza Privata (Consulente + Genitore)",
                    ),
                    ("lawyer_private", "🔒 Avvocato Privato (Avvocato + Genitore)"),
                    ("mediator_private", "🔒 Mediatore Privato (Mediatore + Genitore)"),

                ],
                db_index=True,
                default="family",
                max_length=20,
            ),
        ),
    ]
