# Generated by Django 6.0.3 on 2026-06-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_familymessage_thread_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familymessage",
            name="linked_expense",
        ),
    ]
