# Generated by Django 6.0.3 on 2026-06-11 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_remove_familymessage_linked_expense"),
        ("families", "0010_consultantassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("family", "Famiglia (Tutti)"),
                            ("private", "Privata (1-a-1)"),
                            ("mediation", "Mediazione (Genitori + Mediatore)"),
                            ("legal", "Legale (Genitore + Avvocato)"),
                            ("consultation", "Consulenza (Definita dal mandato)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Es: 'Mediazione Rossi-Bianchi'",
                        max_length=255,
                    ),
                ),
                (
                    "visible_to_roles",
                    models.JSONField(
                        default=list,
                        help_text="Lista di ruoli (es. 'mediator') o ID utente autorizzati",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="families.family",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
