# Generated by Django 6.0.3 on 2026-06-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Se impostato, i permessi di visibilità seguono le regole della Conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chat.conversation",
            ),
        ),
    ]
