# Generated by Django 6.0.3 on 2026-06-24 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_familymessage_conversation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "thread_type",
                    models.CharField(
                        choices=[
                            ("studio_general", "Chat Generale Studio"),
                            ("lawyers_only", "Solo Avvocati"),
                            ("mediators_only", "Solo Mediatori"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Thread Professionisti",
                "verbose_name_plural": "Thread Professionisti",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.professionalthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Professionisti",
                "verbose_name_plural": "Messaggi Professionisti",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="professional_chat/attachments/%Y/%m/"),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.professionalmessage",
                    ),
                ),
            ],
        ),
    ]
