# Generated by Django 6.0.3 on 2026-06-25 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_professionalthread_professionalmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalthread",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Thread Professionisti",
                "verbose_name_plural": "Thread Professionisti",
            },
        ),
        migrations.AddField(
            model_name="professionalthread",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Chi ha creato il thread (per chat private)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_professional_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="professionalthread",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Partecipanti specifici (solo per chat private). Vuoto = chat generale",
                related_name="professional_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="professionalthread",
            name="name",
            field=models.CharField(
                help_text="Nome del thread (per chat private: nomi dei partecipanti)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="professionalthread",
            name="thread_type",
            field=models.CharField(
                choices=[
                    ("studio_general", "Chat Generale Studio"),
                    ("private", "Chat Privata"),
                ],
                default="studio_general",
                help_text="Tipo di thread determina chi può vedere e partecipare",
                max_length=50,
            ),
        ),
    ]
