# Generated by Django 6.0.3 on 2026-06-25 07:46

import core.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_professionalthread_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalattachment",
            options={
                "verbose_name": "Allegato Professionisti",
                "verbose_name_plural": "Allegati Professionisti",
            },
        ),
        migrations.RemoveField(
            model_name="professionalattachment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="professionalattachment",
            name="filename",
        ),
        migrations.AddField(
            model_name="professionalattachment",
            name="encrypted_file",
            field=models.FileField(
                default=django.utils.timezone.now,
                help_text="File criptato (salvato su disco)",
                upload_to="professional_chat/encrypted/%Y/%m/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professionalattachment",
            name="original_filename",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Nome originale del file (per display)",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="professionalattachment",
            name="content_type",
            field=models.CharField(
                default="application/octet-stream",
                help_text="MIME type del file originale",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="professionalattachment",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Dimensione del file in bytes"
            ),
        ),
        migrations.AlterField(
            model_name="professionalmessage",
            name="content",
            field=core.fields.EncryptedTextField(
                blank=True, help_text="Contenuto del messaggio (criptato nel DB)"
            ),
        ),
    ]
