# Generated by Django 6.0.3 on 2026-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="plan",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="starter",
                help_text="Piano di abbonamento scelto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
