# Generated by Django 6.0.3 on 2026-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_plan_userprofile_plan_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data accettazione privacy"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_version_accepted",
            field=models.CharField(
                default="1.0", max_length=10, verbose_name="Versione policy accettata"
            ),
        ),
    ]
