# Generated by Django 6.0.3 on 2026-06-02 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_privacy_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
