# Generated by Django 6.0.3 on 2026-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="partita_iva",
            field=models.CharField(
                blank=True,
                help_text="Obbligatoria per avvocati e professionisti",
                max_length=20,
                verbose_name="Partita IVA",
            ),
        ),
    ]
