# Generated by Django 6.0.3 on 2026-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_partita_iva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                ],
                default="parent",
                max_length=20,
            ),
        ),
    ]
