# Generated by Django 6.0.3 on 2026-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_renew",
            field=models.BooleanField(
                default=True, help_text="Rinnovo automatico mensile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="next_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("active", "✅ Attivo"),
                    ("pending_payment", "⏳ In attesa pagamento"),
                    ("suspended", "🚫 Sospeso"),
                    ("cancelled", "❌ Annullato"),
                ],
                default="active",
                help_text="Stato attuale dell'abbonamento",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_plan",
            field=models.CharField(
                blank=True,
                help_text="Piano futuro (si attiva alla scadenza)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_plan_start",
            field=models.DateTimeField(
                blank=True, help_text="Quando partirà il piano pending", null=True
            ),
        ),
    ]
