# Generated by Django 6.0.3 on 2026-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_userprofile_auto_renew_userprofile_last_payment_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_place_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cf_status",
            field=models.CharField(
                choices=[
                    ("pending", "Da calcolare"),
                    ("calculated", "Calcolato"),
                    ("manual", "Manuale"),
                    ("invalid", "Non valido"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="codice_fiscale",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
