# Generated by Django 6.0.3 on 2026-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_userprofile_birth_place_code_userprofile_cf_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Comune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=100)),
                (
                    "codice_catastale",
                    models.CharField(db_index=True, max_length=4, unique=True),
                ),
                ("provincia", models.CharField(db_index=True, max_length=2)),
            ],
            options={
                "verbose_name": "Comune",
                "verbose_name_plural": "Comuni",
                "ordering": ["nome"],
            },
        ),
    ]
