# Generated by Django 6.0.3 on 2026-05-14 16:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "split_pct_parent_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Se compilato, sovrascrive la % del profilo per questo mantenimento",
                        max_digits=5,
                        null=True,
                        verbose_name="Ripartizione Genitore A",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChildProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "custody_type",
                    models.CharField(
                        choices=[
                            ("shared_custody", "Affidamento condiviso"),
                            ("sole_custody_a", "Affidamento esclusivo Genitore A"),
                            ("sole_custody_b", "Affidamento esclusivo Genitore B"),
                        ],
                        default="shared_custody",
                        max_length=20,
                        verbose_name="Tipo di affidamento",
                    ),
                ),
                (
                    "contribution_pct_parent_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentuale spese a carico del Genitore A (il resto a carico del B)",
                        max_digits=5,
                        null=True,
                        verbose_name="% Contributo Genitore A",
                    ),
                ),
                (
                    "override_split_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Se compilato, sovrascrive la percentuale dell'accordo per questo figlio",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Sovrascrittura % Genitore A",
                    ),
                ),
                (
                    "manual_maintenance_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importo mensile se non è presente una sentenza attiva",
                        max_digits=10,
                        null=True,
                        verbose_name="Importo mantenimento manuale",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
