# Generated by Django 6.0.3 on 2026-05-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildSplitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Vecchia % Genitore A",
                    ),
                ),
                (
                    "new_pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nuova % Genitore A",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Motivazione opzionale della modifica"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_history",
                        to="children.childprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storico Ripartizione",
                "verbose_name_plural": "Storici Ripartizione",
                "ordering": ["-changed_at"],
            },
        ),
    ]
