# Generated by Django 6.0.3 on 2026-05-31 06:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0003_childsplithistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="medical_notes",
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="name",
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="notes",
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="surname",
            field=core.fields.EncryptedCharField(max_length=255),
        ),
    ]
