# Generated by Django 6.0.3 on 2026-06-03 17:35

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "children",
            "0004_childprofile_medical_notes_alter_childprofile_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="childprofile",
            name="notes",
            field=core.fields.EncryptedTextField(blank=True, default="", null=True),
        ),
    ]
