# Generated by Django 6.0.3 on 2026-06-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0005_alter_childprofile_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupport",
            name="support_type",
            field=models.CharField(
                choices=[
                    ("child", "Mantenimento Figli"),
                    ("spouse", "Mantenimento al Coniuge"),
                ],
                default="child",
                max_length=20,
                verbose_name="Tipologia Mantenimento",
            ),
        ),
        migrations.AlterField(
            model_name="childsupport",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supports",
                to="children.childprofile",
                verbose_name="Figlio (se applicabile)",
            ),
        ),
    ]
