# Generated by Django 6.0.3 on 2026-06-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0006_childsupport_support_type_alter_childsupport_child"),
        ("families", "0010_consultantassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupport",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supports",
                to="families.family",
                verbose_name="Famiglia di riferimento",
            ),
        ),
        migrations.AlterField(
            model_name="childsupport",
            name="support_type",
            field=models.CharField(
                choices=[
                    ("child", "Mantenimento Figli"),
                    ("spouse", "Mantenimento al Coniuge"),
                ],
                default="child",
                max_length=20,
                verbose_name="Tipologia",
            ),
        ),
    ]
