# Generated by Django 6.0.3 on 2026-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0007_childsupport_family_alter_childsupport_support_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupport",
            name="payer_role",
            field=models.CharField(
                choices=[
                    ("parent_a", "Genitore A versa a Genitore B"),
                    ("parent_b", "Genitore B versa a Genitore A"),
                ],
                default="parent_a",
                help_text="Stabilito dal giudice nella sentenza",
                max_length=20,
                verbose_name="Chi versa il mantenimento",
            ),
        ),
    ]
