# Generated by Django 6.0.3 on 2026-06-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0008_childsupport_payer_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In attesa di accettazione"),
                    ("active", "Attivo e Accettato"),
                    ("rejected", "Rifiutato"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
