# Generated by Django 6.0.3 on 2026-06-19 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0009_childsupport_status"),
        ("families", "0013_childsupportagreement_certified_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="childprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("family", "name", "surname", "birth_date"),
                name="unique_active_child_per_family",
            ),
        ),
    ]
