# Generated by Django 6.0.3 on 2026-06-20 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0010_childprofile_unique_active_child_per_family"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupport",
            name="certified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="childsupport",
            name="certified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Avvocato o mediatore che ha certificato l'accordo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certified_child_supports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
