# Generated by Django 6.0.3 on 2026-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0011_childsupport_certified_at_childsupport_certified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupport",
            name="decree_date",
            field=models.DateField(
                blank=True,
                help_text="Data di emissione della sentenza",
                null=True,
                verbose_name="Data Sentenza",
            ),
        ),
        migrations.AddField(
            model_name="childsupport",
            name="decree_file",
            field=models.FileField(
                blank=True,
                help_text="Carica la sentenza che autorizza la modifica del mantenimento",
                null=True,
                upload_to="legal/decrees/child_support/",
                verbose_name="Sentenza/Decreto",
            ),
        ),
        migrations.AddField(
            model_name="childsupport",
            name="decree_number",
            field=models.CharField(
                blank=True,
                help_text="Es: Sentenza n. 123/2026",
                max_length=100,
                verbose_name="Numero Sentenza",
            ),
        ),
    ]
