# Generated by Django 6.0.3 on 2026-05-14 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar_app", "0001_initial"),
        ("children", "0002_initial"),
        ("documents", "0001_initial"),
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="children",
            field=models.ManyToManyField(
                blank=True, related_name="calendar_events", to="children.childprofile"
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="families.family",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="linked_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events",
                to="families.childsupportagreement",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_versions",
                to="calendar_app.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="eventattachment",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="eventattachment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calendar_app.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="eventcomment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="calendar_app.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="eventcomment",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_event_calendar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calendar_app.calendarevent",
            ),
        ),
    ]
