# Generated by Django 6.0.3 on 2026-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="linked_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "📅 Creato manualmente"),
                    ("chat", "💬 Generato da Chat"),
                    ("expense", "💰 Generato da Spesa"),
                    ("agreement", "📄 Generato da Accordo"),
                ],
                db_index=True,
                default="manual",
                max_length=20,
            ),
        ),
    ]
