# Generated by Django 6.0.3 on 2026-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0003_calendarevent_linked_id_calendarevent_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("custody", "🏠 Affidamento / Cambio casa"),
                    ("support", "💰 Mantenimento"),
                    ("school", "🏫 Scuola / Gita Scolastica"),
                    ("medical", "🏥 Medico / Terapia"),
                    ("expense", "💰 Spesa / Rimborso"),
                    ("legal", "⚖️ Legale / Udienza"),
                    ("holiday_a", "🏖️ Ferie Genitore A"),
                    ("holiday_b", "🏖️ Ferie Genitore B"),
                    ("child_event", "⚽ Evento Figlio (Sport/Compleanno)"),
                    ("mediation", "🤝 Riunione Mediazione"),
                    ("consulting", "💼 Riunione Consulenza"),
                    ("other", "📌 Altro"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
