# Generated by Django 6.0.3 on 2026-06-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0004_alter_calendarevent_event_type"),
        ("expenses", "0004_remove_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="expense_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoria spesa se l'evento genera una spesa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="linked_expense",
            field=models.ForeignKey(
                blank=True,
                help_text="Spesa generata automaticamente da questo evento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_events",
                to="expenses.expense",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
