# Generated by Django 6.0.3 on 2026-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0005_calendarevent_expense_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="linked_agreement",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "📅 Creato manualmente"),
                    ("chat", "💬 Generato da Chat"),
                    ("expense", "💰 Generato da Spesa"),
                    ("agreement", "📄 Generato da Accordo (legacy)"),
                    ("child_support", "💰 Mantenimento Figli"),
                    ("spouse_support", "💰 Mantenimento Coniuge"),
                ],
                db_index=True,
                default="manual",
                max_length=20,
            ),
        ),
    ]
