# Generated by Django 6.0.3 on 2026-06-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0006_remove_calendarevent_linked_agreement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="google_event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID evento su Google Calendar (se sincronizzato)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GoogleCalendarToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "token_uri",
                    models.URLField(default="https://oauth2.googleapis.com/token"),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("scopes", models.TextField(help_text="Scopes separati da spazio")),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="ID calendario Google (default: primary)",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Google Calendar",
                "verbose_name_plural": "Token Google Calendar",
            },
        ),
    ]
