# Generated by Django 6.0.3 on 2026-06-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0007_calendarevent_google_event_id_googlecalendartoken"),
        ("families", "0014_spousesupportagreement_payer_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "👥 Riunione cliente"),
                            ("court", "⚖️ Udienza"),
                            ("consultation", "💼 Consulenza"),
                            ("mediation", "🤝 Mediazione"),
                            ("deadline", "📅 Scadenza legale"),
                            ("other", "📌 Altro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Luogo dell'appuntamento", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "google_event_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_events",
                        to="families.family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
