# Generated by Django 6.0.3 on 2026-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="document",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Se attivo, il documento sarà visibile solo ai partecipanti della chat privata.",
                verbose_name="Documento Riservato",
            ),
        ),
    ]
