# Generated by Django 6.0.3 on 2026-05-31 06:02

import core.fields
import core.storage
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_options_document_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=core.storage.EncryptedFileSystemStorage(
                    location="media/encrypted_docs"
                ),
                upload_to=documents.models.family_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="file",
            field=models.FileField(
                storage=core.storage.EncryptedFileSystemStorage(
                    location="media/encrypted_docs"
                ),
                upload_to=documents.models.family_document_path,
            ),
        ),
    ]
