# Generated by Django 6.0.3 on 2026-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_file_alter_document_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
