# Generated by Django 6.0.3 on 2026-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentapproval",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                    ("mediator_a", "Mediatore A"),
                    ("mediator_b", "Mediatore B"),
                    ("consultant_a", "Consulente A"),
                    ("consultant_b", "Consulente B"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentsignature",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                    ("mediator_a", "Mediatore A"),
                    ("mediator_b", "Mediatore B"),
                    ("consultant_a", "Consulente A"),
                    ("consultant_b", "Consulente B"),
                ],
                max_length=20,
            ),
        ),
    ]
