# Generated by Django 6.0.3 on 2026-06-11 08:22

import core.fields
import core.storage
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_alter_documentapproval_role_and_more"),
        ("families", "0010_consultantassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediationAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    core.fields.EncryptedCharField(
                        max_length=255, verbose_name="Titolo dell'accordo"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        verbose_name="Descrizione o oggetto della mediazione",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("review", "In revisione dalle parti"),
                            ("signing", "In fase di firma"),
                            ("completed", "Completato e Firmato"),
                            ("archived", "Archiviato"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "final_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.storage.EncryptedFileSystemStorage(
                            location="media/encrypted_docs"
                        ),
                        upload_to=documents.models.mediation_agreement_path,
                        verbose_name="PDF Accordo Firmato",
                    ),
                ),
                (
                    "pdf_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Generato automaticamente al caricamento del PDF finale.",
                        max_length=64,
                        verbose_name="Hash di integrità del PDF",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediation_agreements",
                        to="families.family",
                    ),
                ),
                (
                    "mediator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__role": "mediator"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mediated_agreements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mediatore incaricato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accordo di Mediazione",
                "verbose_name_plural": "Accordi di Mediazione",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediationAgreementSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_at_signing",
                    models.CharField(
                        choices=[
                            ("parent", "Genitore"),
                            ("lawyer", "Avvocato"),
                            ("mediator", "Mediatore"),
                            ("consultant", "Consulente"),
                            ("parent_a", "Genitore A"),
                            ("parent_b", "Genitore B"),
                            ("lawyer_a", "Avvocato A (del Genitore A)"),
                            ("lawyer_b", "Avvocato B (del Genitore B)"),
                        ],
                        help_text="Ruolo dell'utente al momento della firma",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        verbose_name="Indirizzo IP al momento della firma",
                    ),
                ),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signature_data",
                    core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Token o metadati del provider di firma digitale",
                        max_length=500,
                        verbose_name="Dati firma crittografati",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="documents.mediationagreement",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediation_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma Accordo di Mediazione",
                "verbose_name_plural": "Firme Accordi di Mediazione",
                "ordering": ["signed_at"],
                "unique_together": {("agreement", "signer")},
            },
        ),
    ]
