# Generated by Django 6.0.3 on 2026-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_mediationagreement_mediationagreementsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Data di scadenza del documento (opzionale). Se impostata, genererà un avviso.",
                null=True,
                verbose_name="Data di scadenza",
            ),
        ),
    ]
