# Generated by Django 6.0.3 on 2026-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_document_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dati strutturati estratti automaticamente dal PDF (mantenimento, affidamento, ecc.)",
                verbose_name="Dati estratti",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("payslip", "Busta paga"),
                    ("tax_return", "Dichiarazione redditi"),
                    ("chat", "Documento chat"),
                    ("agreement", "Accordo"),
                    ("minutes", "Verbale"),
                    ("payment_proof", "Prova di pagamento"),
                    ("ruling", "📜 Sentenza"),
                    ("generic", "Documento generico"),
                ],
                default="generic",
                max_length=20,
            ),
        ),
    ]
