# Generated by Django 6.0.3 on 2026-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_document_extracted_data_alter_document_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentapproval",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("spouse", "Coniuge"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentsignature",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("spouse", "Coniuge"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mediationagreementsignature",
            name="role_at_signing",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("spouse", "Coniuge"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                help_text="Ruolo dell'utente al momento della firma",
                max_length=20,
            ),
        ),
    ]
