"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# ✅ PERMETTI HTTP PER OAUTH2 IN SVILUPPO (NON USARE IN PRODUZIONE!)
import os
#os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
from pathlib import Path

import dj_database_url
from celery.schedules import crontab
from decouple import config
from dotenv import load_dotenv
load_dotenv()
from django.conf.global_settings import EMAIL_USE_SSL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", 'fallback-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

#CSRF_TRUSTED_ORIGINS = ["https://*.herokuapp.com"]
CSRF_TRUSTED_ORIGINS = [
    "https://coparentmanager.com",
    "https://www.coparentmanager.com",
	"https://*.coparentmanager.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ✅ HOSTS (Render usa .onrender.com)
ALLOWED_HOSTS = [
	"coparentmanager.com",
    "www.coparentmanager.com",
	"coparent-manager.onrender.com",
	".coparentmanager.com",
]

if os.getenv("ENV") == "production":
    FRONTEND_DOMAIN = "https://coparentmanager.com"
else:
    FRONTEND_DOMAIN = "http://127.0.0.1:8000"
# Application definition

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "cf-cache",
    }
} 

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms", # new
	"crispy_bootstrap5",
    'core',
    'accounts',
    'families.apps.FamiliesConfig',
    'children',
    "calendar_app.apps.CalendarAppConfig",
    'expenses',
    'chat',
    'documents',
    'notifications',
    "django.contrib.humanize",
]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',  # ✅ Questo trova i file di django_select2
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SubscriptionMiddleware',
]

ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'families.context_processors.family_membership',
                'families.context_processors.lawyer_nav_context',
                'families.context_processors.family_context',
                'core.context_processors.breadcrumbs',
                'core.context_processors.subscription_context',
                'core.context_processors.dashboard_context',
            ],
        },
    },
]

## ✅ Database: PostgreSQL su Render, SQLite in locale
if os.environ.get("RENDER") or os.environ.get("PRODUCTION"):
    # Produzione: usa le variabili DB_* impostate su Render
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }
else:
    # Locale: SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

X_FRAME_OPTIONS = 'SAMEORIGIN'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media" 
#DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"   online
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
#Log errori inviati via email (admin)
#Monitoraggio uptime (UptimeRobot, Healthchecks.io)
#Alert se il sito va giù
#Log accessi sospetti (IP strani, tentativi login falliti)
if DEBUG:
    # 🛠️ IN SVILUPPO: Logga solo sulla console, nessun file necessario
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
            },
            'accounts': {  # Log della tua app accounts
                'handlers': ['console'],
                'level': 'DEBUG',
            },
            'families': {  # Log della tua app families
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }
else:
    # 🚀 IN PRODUZIONE
    LOG_DIR = BASE_DIR / 'logs'
    LOG_DIR.mkdir(exist_ok=True)

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': LOG_DIR / 'error.log',
                'formatter': 'verbose',
            },
            'mail_admins': {
                'level': 'ERROR',
                'class': 'django.utils.log.AdminEmailHandler',
            },
        },
        'root': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'chat': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': False,
            },
            'notifications': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': False,
            },
            'families': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
AUTH_USER_MODEL = 'accounts.User'



STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]

# ✅ WhiteNoise per static files in produzione
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'#'mailjet.backends.MailjetBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
MAILJET_API_KEY = os.getenv("MAILJET_API_KEY")
MAILJET_SECRET_KEY = os.getenv("MAILJET_SECRET_KEY")

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"


EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")    #os.getenv("MAILJET_API_KEY")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD") #os.getenv("MAILJET_SECRET_KEY")
#DEFAULT_FROM_EMAIL = "no-reply@mailjet.com"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@coparentmanager.com"
SERVER_EMAIL = EMAIL_HOST_USER or "noreply@coparentmanager.com"

# ✅ Se non ci sono credenziali email, usa console backend
if not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  produzione
# Sicurezza extra

#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = True
# In fondo al tuo settings.py

if DEBUG:
    # Ambiente di SVILUPPO: usa HTTP normale
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
else:
    # Ambiente di PRODUZIONE: forza HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 anno
	


# ⚡ CONFIGURAZIONE CELERY
if DEBUG:
    CELERY_BROKER_URL = "redis://localhost:6379/0"  # Broker standard (Redis)
    CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
    CELERY_ACCEPT_CONTENT = ["json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = TIME_ZONE  # Usa il tuo fuso orario già definito

    # 🧪 FALLBACK SVILUPPO (se NON hai Redis installato):
    # Esegue i task in modo sincrono, senza bisogno di broker/worker
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_BEAT_SCHEDULE = {
        'send-event-reminders-every-5-minutes': {
            'task': 'calendar_app.tasks.send_event_reminder',
            'schedule': crontab(minute='*/20'),  # ogni 20 minuti
            'options': {'expires': 1200},  # evita accavallamenti se il worker è lento
        },
        'check-document-expirations-daily': {
            'task': 'notifications.tasks.check_document_expirations',
            'schedule': crontab(hour=8, minute=0), # Ogni giorno alle 08:00
        },
        'check-pending-agreements-daily': {
            'task': 'notifications.tasks.check_pending_agreements',
            'schedule': crontab(hour=9, minute=0), # Ogni giorno alle 09:00
        },
        'check-imminent-events-hourly': {
            'task': 'notifications.tasks.check_imminent_events',
            'schedule': crontab(minute=0), # Ogni ora, al minuto 0
        },
    }
else:
    # Produzione: esegui task in modo sincrono (senza Redis)
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


PRIVACY_VERSION = "1.0"  # Incrementa a "1.1", "2.0" quando aggiorni la policy
ENCRYPTION_KEY=os.environ.get("ENCRYPTION_KEY")

# ========================================
# GOOGLE CALENDAR API
# ========================================
GOOGLE_CALENDAR_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', default='')
GOOGLE_CALENDAR_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', default='')
#GOOGLE_CALENDAR_REDIRECT_URI = 'https://coparentmanager.com/calendar/oauth/google/callback/'
if DEBUG:
    GOOGLE_CALENDAR_REDIRECT_URI = 'https://coparentmanager.com/calendar/oauth/google/callback/'
else:
    GOOGLE_CALENDAR_REDIRECT_URI = 'https://coparentmanager.com/calendar/oauth/google/callback/'
GOOGLE_CALENDAR_SCOPES = [
    'https://www.googleapis.com/auth/calendar.events',
    'https://www.googleapis.com/auth/calendar',
]
