# Generated by Django 6.0.3 on 2026-05-14 16:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="Codice famiglia"
                    ),
                ),
                (
                    "creator_role",
                    models.CharField(
                        choices=[
                            ("parent_a", "Genitore A"),
                            ("lawyer_a", "Avvocato A"),
                        ],
                        default="parent_a",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildSupportAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decree_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numero sentenza/accordo",
                    ),
                ),
                (
                    "decree_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data sentenza"
                    ),
                ),
                (
                    "decree_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal/decrees/",
                        verbose_name="File sentenza",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Importo mensile totale",
                    ),
                ),
                (
                    "split_pct_parent_a",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% a carico Genitore A",
                    ),
                ),
                (
                    "payment_day",
                    models.PositiveIntegerField(
                        help_text="Es: 5 per il 5 di ogni mese",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Giorno del mese",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Decorrenza")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Di default fino al compimento della maggiore età",
                        null=True,
                        verbose_name="Scadenza (opzionale)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "children",
                    models.ManyToManyField(
                        related_name="support_agreements", to="children.childprofile"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_versions",
                        to="families.childsupportagreement",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_agreements",
                        to="families.family",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("parent_a", "Genitore A"),
                            ("parent_b", "Genitore B"),
                            ("lawyer_a", "Avvocato A"),
                            ("lawyer_b", "Avvocato B"),
                            ("mediator", "Mediatore"),
                            ("consultant", "Consulente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="families.family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "user"), name="unique_family_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("parent_a", "Genitore A"),
                            ("parent_b", "Genitore B"),
                            ("lawyer_a", "Avvocato A"),
                            ("lawyer_b", "Avvocato B"),
                            ("mediator", "Mediatore"),
                            ("consultant", "Consulente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa"),
                            ("accepted", "Accettato"),
                            ("expired", "Scaduto"),
                            ("cancelled", "Annullato"),
                            ("revoked", "Revocato"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("resend_count", models.PositiveIntegerField(default=0)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="families.family",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="families_in_email_9a40d9_idx"),
                    models.Index(fields=["token"], name="families_in_token_11f518_idx"),
                    models.Index(
                        fields=["status"], name="families_in_status_58e611_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "pending"), ("email__isnull", False)
                        ),
                        fields=("family", "email"),
                        name="unique_pending_invitation",
                    )
                ],
            },
        ),
    ]
