# Generated by Django 6.0.3 on 2026-05-17 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="familymember",
            constraint=models.UniqueConstraint(
                fields=("family", "role"), name="unique_family_role"
            ),
        ),
    ]
