# Generated by Django 6.0.3 on 2026-05-28 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0002_familymember_unique_family_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together={("family", "user")},
        ),
    ]
