# Generated by Django 6.0.3 on 2026-05-31 06:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0003_alter_familymember_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="name",
            field=core.fields.EncryptedCharField(max_length=255),
        ),
    ]
