# Generated by Django 6.0.3 on 2026-06-04 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0005_alter_familymember_role_alter_invitation_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Attivo"),
                            ("grace_period", "Periodo di grazia (5 giorni)"),
                            ("suspended", "Sospeso"),
                            ("cancelled", "Cancellato"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("subscription_end", models.DateTimeField()),
                ("grace_period_end", models.DateTimeField(blank=True, null=True)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                ("next_payment_date", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_provider_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscription_end"],
                        name="families_pa_subscri_17e07d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="families_pa_status_484bd3_idx"
                    ),
                ],
            },
        ),
    ]
