# Generated by Django 6.0.3 on 2026-06-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0006_paymentsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="families.family",
            ),
        ),
    ]
