# Generated by Django 6.0.3 on 2026-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0007_alter_invitation_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                max_length=20,
            ),
        ),
    ]
