# Generated by Django 6.0.3 on 2026-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0008_alter_familymember_role_alter_invitation_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsubscription",
            name="current_plan",
            field=models.CharField(default="starter", max_length=20),
        ),
        migrations.AddField(
            model_name="paymentsubscription",
            name="pending_plan",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentsubscription",
            name="pending_plan_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
