# Generated by Django 6.0.3 on 2026-06-11 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0009_paymentsubscription_current_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            (
                                "individual",
                                "Individuale (su richiesta di un singolo genitore)",
                            ),
                            ("family", "Familiare (accordo congiunto tra i genitori)"),
                            (
                                "ctu",
                                "CTU (Consulente Tecnico d'Ufficio - Nomina Tribunale)",
                            ),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Tipo di incarico",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data inizio incarico")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data fine incarico"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Incarico attivo"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Es: Numero di ruolo CTU, oggetto specifico della consulenza, ecc.",
                        verbose_name="Note sull'incarico",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "consultant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Consulente incaricato",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_assignments",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incarico Consulente",
                "verbose_name_plural": "Incarichi Consulenti",
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("family", "assignment_type"),
                        name="unique_active_assignment_per_family_and_type",
                    )
                ],
            },
        ),
    ]
