# Generated by Django 6.0.3 on 2026-06-19 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0010_consultantassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpouseSupportAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decree_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numero sentenza/accordo",
                    ),
                ),
                (
                    "decree_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data sentenza"
                    ),
                ),
                (
                    "decree_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal/spouse_decrees/",
                        verbose_name="File sentenza",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo mensile del mantenimento (es: €500)",
                        max_digits=10,
                        verbose_name="Importo mensile",
                    ),
                ),
                (
                    "payment_day",
                    models.PositiveIntegerField(
                        help_text="Es: 5 per il 5 di ogni mese",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Giorno del mese",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Decorrenza")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Obbligatoria per mantenimento coniuge",
                        verbose_name="Scadenza",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex coniuge che riceve il mantenimento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spouse_support_beneficiary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avvocato o mediatore che ha certificato l'accordo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_spouse_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spouse_support_agreements",
                        to="families.family",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_spouse_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_versions",
                        to="families.spousesupportagreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accordo Mantenimento Coniuge",
                "verbose_name_plural": "Accordi Mantenimento Coniuge",
                "ordering": ["-start_date"],
            },
        ),
    ]
