# Generated by Django 6.0.3 on 2026-06-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0011_spousesupportagreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spousesupportagreement",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Se vuota, il mantenimento è a tempo indeterminato. Se inserita, gli eventi calendario dopo questa data verranno eliminati.",
                null=True,
                verbose_name="Scadenza (opzionale)",
            ),
        ),
    ]
