# Generated by Django 6.0.3 on 2026-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0013_childsupportagreement_certified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spousesupportagreement",
            name="payer_role",
            field=models.CharField(
                choices=[
                    ("parent_a", "Genitore A versa a Genitore B"),
                    ("parent_b", "Genitore B versa a Genitore A"),
                ],
                default="parent_a",
                help_text="Stabilito dal giudice nella sentenza",
                max_length=20,
                verbose_name="Chi versa il mantenimento",
            ),
        ),
        migrations.AlterField(
            model_name="familymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("spouse", "Coniuge"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Genitore"),
                    ("lawyer", "Avvocato"),
                    ("mediator", "Mediatore"),
                    ("consultant", "Consulente"),
                    ("spouse", "Coniuge"),
                    ("parent_a", "Genitore A"),
                    ("parent_b", "Genitore B"),
                    ("lawyer_a", "Avvocato A (del Genitore A)"),
                    ("lawyer_b", "Avvocato B (del Genitore B)"),
                ],
                max_length=20,
            ),
        ),
    ]
