# Generated by Django 6.0.3 on 2026-05-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="target_model",
            field=models.CharField(
                blank=True,
                help_text="Es: 'Expense', 'FamilyMessage'",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
