# Generated by Django 6.0.3 on 2026-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("chat_private", "💬 Messaggio Privato"),
                    ("expense_pending", "💰 Spesa in Attesa"),
                    ("expense_rejected", "🔴 Spesa Rifiutata"),
                    ("expense_paid", "✅ Spesa Pagata"),
                    ("event_reminder", "📅 Promemoria Evento"),
                    ("invite", "📨 Nuovo Invito"),
                    ("document_expiring", "📄 Documento in Scadenza"),
                    ("agreement_pending", "✍️ Accordo in Attesa di Firma"),
                    ("event_imminent", "⏰ Evento Imminente"),
                    ("calendar_event_created", "📅 Nuovo Evento Calendario"),
                ],
                max_length=30,
            ),
        ),
    ]
